name: flutter_firebase_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.0
  firebase_core: ^3.0.0
  flow_builder: ^0.1.0
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.8.0
  google_fonts: ^6.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
